import { GAME } from './config.js';

export class Renderer {
  constructor(canvas){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.shake=0;this.flash=0;this.particles=[];this.w=1;this.h=1;}
  resize(){const dpr=Math.min(2,devicePixelRatio||1);const r=this.canvas.getBoundingClientRect();const w=Math.max(1,r.width||innerWidth||1),h=Math.max(1,r.height||innerHeight||1);this.canvas.width=Math.max(1,Math.floor(w*dpr));this.canvas.height=Math.max(1,Math.floor(h*dpr));this.ctx.setTransform(dpr,0,0,dpr,0,0);this.w=w;this.h=h;}
  impact(x,y,color='#d8f7ff'){for(let i=0;i<7;i++){const a=Math.random()*Math.PI*2,s=35+Math.random()*90;this.particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,t:.28,color});}}
  updateFx(dt){for(const p of this.particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.t-=dt;}this.particles=this.particles.filter(p=>p.t>0);this.shake=Math.max(0,this.shake-dt*24);this.flash=Math.max(0,this.flash-dt*3);}
  draw(game){const c=this.ctx,w=this.w,h=this.h;c.clearRect(0,0,w,h);c.save();if(this.shake>0)c.translate((Math.random()-.5)*this.shake,(Math.random()-.5)*this.shake);
    const g=c.createLinearGradient(0,0,0,h);g.addColorStop(0,'#1b2531');g.addColorStop(.55,'#141b24');g.addColorStop(1,'#0b1118');c.fillStyle=g;c.fillRect(0,0,w,h);
    this.drawRuins(c,w,h);this.drawPath(c,game.path);this.drawBuildSpots(c,game.buildSpots,game.buildMode,game.mana>=GAME.towerCost);this.drawCrystal(c,game.crystal);for(const t of game.towers)this.drawTower(c,t);for(const p of game.projectiles)this.drawProjectile(c,p);for(const e of game.enemies)if(!e.dead)this.drawEnemy(c,e);this.drawHero(c,game.hero);for(const p of this.particles){c.globalAlpha=Math.max(0,p.t/.28);c.fillStyle=p.color;c.beginPath();c.arc(p.x,p.y,3.2,0,Math.PI*2);c.fill();}c.globalAlpha=1;
    c.restore(); if(this.flash>0){c.fillStyle=`rgba(255,80,70,${this.flash*.16})`;c.fillRect(0,0,w,h);} }
  drawRuins(c,w,h){c.fillStyle='rgba(92,105,111,.16)';for(let i=0;i<12;i++){const x=(i*137)%w,y=88+((i*83)%Math.max(1,h-150));c.fillRect(x,y,42,18);c.fillRect(x+8,y-18,26,18);}c.strokeStyle='rgba(130,170,178,.09)';c.lineWidth=1;for(let x=0;x<w;x+=48){c.beginPath();c.moveTo(x,0);c.lineTo(x+80,h);c.stroke();}}
  drawPath(c,path){c.lineCap='round';c.lineJoin='round';c.strokeStyle='rgba(121,93,65,.62)';c.lineWidth=68;c.beginPath();c.moveTo(path[0].x,path[0].y);for(const p of path.slice(1))c.lineTo(p.x,p.y);c.stroke();c.strokeStyle='rgba(214,171,102,.15)';c.lineWidth=4;c.setLineDash([12,18]);c.stroke();c.setLineDash([]);}
  drawBuildSpots(c,spots,mode,afford){for(const s of spots){c.beginPath();c.arc(s.x,s.y,28,0,Math.PI*2);c.fillStyle=s.built?'rgba(40,55,63,.45)':mode&&afford?'rgba(67,209,235,.18)':'rgba(100,130,145,.09)';c.fill();c.strokeStyle=s.built?'rgba(110,130,140,.18)':mode&&afford?'rgba(116,230,250,.78)':'rgba(170,190,200,.18)';c.lineWidth=2;c.stroke();if(!s.built){c.fillStyle='rgba(210,232,240,.45)';c.font='800 11px system-ui';c.textAlign='center';c.fillText(mode?'TAP TO BUILD':'RUNE',s.x,s.y+4);}}}
  drawCrystal(c,o){c.save();c.translate(o.x,o.y);c.shadowBlur=28;c.shadowColor='#68e7ff';c.fillStyle='#99efff';c.beginPath();c.moveTo(0,-34);c.lineTo(24,-5);c.lineTo(13,32);c.lineTo(-16,26);c.lineTo(-25,-7);c.closePath();c.fill();c.shadowBlur=0;c.strokeStyle='rgba(255,255,255,.82)';c.stroke();c.restore();}
  drawHero(c,h){c.save();c.translate(h.x,h.y);c.fillStyle='#d9e4ed';c.beginPath();c.arc(0,0,h.r,0,Math.PI*2);c.fill();c.fillStyle='#365d7a';c.beginPath();c.arc(-4,-4,h.r*.62,0,Math.PI*2);c.fill();c.strokeStyle='#eefaff';c.lineWidth=4;c.beginPath();c.moveTo(h.dir.x*12,h.dir.y*12);c.lineTo(h.dir.x*27,h.dir.y*27);c.stroke();c.restore();}
  drawEnemy(c,e){c.save();c.translate(e.x,e.y);c.fillStyle='#718c4b';c.beginPath();c.arc(0,0,e.r,0,Math.PI*2);c.fill();c.fillStyle='#26331d';c.fillRect(-7,-5,4,4);c.fillRect(3,-5,4,4);c.fillStyle='rgba(0,0,0,.6)';c.fillRect(-18,-27,36,5);c.fillStyle='#e35a53';c.fillRect(-18,-27,36*(e.hp/e.maxHp),5);c.restore();}
  drawTower(c,t){c.save();c.translate(t.x,t.y);c.fillStyle='#59636a';c.fillRect(-14,-7,28,24);c.fillStyle='#8b6b43';c.fillRect(-5,-24,10,24);c.strokeStyle='#d6c6a2';c.lineWidth=3;c.beginPath();c.arc(0,-18,11,-1.2,1.2);c.stroke();c.restore();}
  drawProjectile(c,p){c.fillStyle='#ffe6a8';c.shadowBlur=12;c.shadowColor='#ffd27a';c.beginPath();c.arc(p.x,p.y,p.r,0,Math.PI*2);c.fill();c.shadowBlur=0;}
}
